# Generated by Django 5.2.17 on 2026-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='المفتاح')),
                ('value', models.CharField(max_length=500, verbose_name='القيمة')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='الوصف')),
            ],
        ),
    ]
