# Generated by Django 5.2.17 on 2026-10-02 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('history', '0004_alter_historicalevent_date_precision'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('focus', models.CharField(blank=True, max_length=800)),
                ('status', models.CharField(choices=[('READY', 'جاهز للاستخراج'), ('RUNNING', 'جارٍ الاستخراج'), ('REVIEW', 'جاهز للمراجعة'), ('FAILED', 'تعذر الاستخراج'), ('APPLIED', 'حُفظت المسودات')], default='READY', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('selected_chunk_ids', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_claim_ids', models.JSONField(default=list)),
                ('created_passage_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history.historicalevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.historicalsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
