# Generated by Django 5.2.17 on 2026-10-03 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_providerconfiguration'),
        ('dashboard', '0002_extractionrun'),
        ('sources', '0002_alter_historicalsource_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'في قائمة التحليل'), ('RUNNING', 'جارٍ تحليل المصدر'), ('REVIEW', 'جاهز للمراجعة'), ('PARTIAL', 'تحليل جزئي'), ('FAILED', 'تعذر التحليل'), ('APPLIED', 'حُفظت اختيارات المحرر')], default='QUEUED', max_length=16)),
                ('entities', models.JSONField(default=list)),
                ('processed_chunk_ids', models.JSONField(default=list)),
                ('failed_chunk_ids', models.JSONField(default=list)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('saved_entity_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ai.providerconfiguration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='sources.historicalsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
