# Generated by Django 5.2.17 on 2026-10-01 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.entity'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explorationhistory',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.entity'),
        ),
        migrations.AddField(
            model_name='explorationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='unique_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='explorationhistory',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='unique_visit'),
        ),
    ]
