# Generated by Django 5.2.17 on 2026-10-01 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0002_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField(verbose_name='الادعاء')),
                ('claim_type', models.CharField(choices=[('FACT', 'حقيقة موثقة'), ('INTERPRETATION', 'تفسير'), ('MULTIPLE_ACCOUNTS', 'اختلاف روايات'), ('UNCERTAIN', 'غير محسوم')], default='UNCERTAIN', max_length=20, verbose_name='التصنيف')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], db_index=True, default='DRAFT', max_length=12, verbose_name='حالة المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('is_demo', models.BooleanField(default=False, verbose_name='مثال تجريبي')),
                ('ai_suggested', models.BooleanField(default=False, verbose_name='اقتراح ذكاء اصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='history.historicalevent', verbose_name='الحدث')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.historicalperson', verbose_name='الشخصية')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.historicalplace', verbose_name='المكان')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_text', models.TextField(verbose_name='نص الدليل')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الصفحة')),
                ('section', models.CharField(blank=True, max_length=240, verbose_name='موضع الدليل')),
                ('support_type', models.CharField(choices=[('SUPPORTS', 'يدعم'), ('PARTIALLY_SUPPORTS', 'يدعم جزئيًا'), ('CONTRADICTS', 'يعارض'), ('CONTEXTUALIZES', 'يقدم سياقًا')], default='SUPPORTS', max_length=20, verbose_name='نوع الدعم')),
                ('notes', models.TextField(blank=True, verbose_name='السياق والملاحظات')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.historicalsource', verbose_name='المصدر')),
                ('source_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sources.sourcechunk', verbose_name='المقطع')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='knowledge.historicalclaim', verbose_name='الادعاء')),
            ],
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('PRECEDED_BY', 'سبقه'), ('FOLLOWED_BY', 'تلاه'), ('PARTICIPATED_IN', 'شارك في'), ('OCCURRED_AT', 'وقع في'), ('CAUSED_BY', 'نتج عن'), ('RESULTED_IN', 'أدى إلى'), ('RELATED_TO', 'مرتبط بـ'), ('MENTIONED_IN', 'ورد في'), ('SUPPORTED_BY', 'يدعمه'), ('TRAVELLED_TO', 'انتقل إلى'), ('CONTEMPORARY_WITH', 'عاصر')], max_length=24, verbose_name='العلاقة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=12, verbose_name='حالة المراجعة')),
                ('notes', models.TextField(blank=True, verbose_name='السياق')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='history.entity', verbose_name='من')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='history.entity', verbose_name='إلى')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_entity', 'to_entity', 'relation_type'), name='unique_relationship'), models.CheckConstraint(condition=models.Q(('from_entity', models.F('to_entity')), _negated=True), name='no_self_relation')],
            },
        ),
    ]
