# Generated by Django 5.2.17 on 2026-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrelationship',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=12, verbose_name='حالة المراجعة'),
        ),
        migrations.AlterField(
            model_name='historicalclaim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف'), ('REJECTED', 'مرفوض')], db_index=True, default='DRAFT', max_length=12, verbose_name='حالة المراجعة'),
        ),
    ]
