# Generated by Django 5.2.17 on 2026-10-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_entityrelationship_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrelationship',
            name='supporting_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_relationships', to='knowledge.historicalclaim', verbose_name='الادعاء الداعم للرابطة'),
        ),
        migrations.AlterField(
            model_name='entityrelationship',
            name='relation_type',
            field=models.CharField(choices=[('PRECEDED_BY', 'سبقه'), ('FOLLOWED_BY', 'تلاه'), ('PARTICIPATED_IN', 'شارك في'), ('OCCURRED_AT', 'وقع في'), ('CAUSED_BY', 'نتج عن'), ('RESULTED_IN', 'أدى إلى'), ('RELATED_TO', 'مرتبط بـ'), ('MENTIONED_IN', 'ورد في'), ('SUPPORTED_BY', 'يدعمه'), ('TRAVELLED_TO', 'انتقل إلى'), ('CONTEMPORARY_WITH', 'عاصر'), ('NARRATED', 'روى خبر')], max_length=24, verbose_name='العلاقة'),
        ),
    ]
