# Generated by Django 5.2.17 on 2026-10-01 08:24

import apps.sources.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSource',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.entity')),
                ('author', models.CharField(blank=True, max_length=240, verbose_name='المؤلف')),
                ('source_type', models.CharField(choices=[('book', 'كتاب'), ('article', 'مقال'), ('manuscript', 'مخطوط'), ('research', 'بحث'), ('digital', 'مصدر رقمي'), ('other', 'غير ذلك')], default='book', max_length=20, verbose_name='نوع المصدر')),
                ('publication_information', models.TextField(blank=True, verbose_name='بيانات الطبعة والنشر')),
                ('language', models.CharField(default='العربية', max_length=50, verbose_name='اللغة')),
                ('url', models.URLField(blank=True, verbose_name='رابط المصدر')),
                ('file', models.FileField(blank=True, upload_to='sources/%Y/%m/', validators=[apps.sources.validators.validate_document], verbose_name='ملف المصدر')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='مصدر معتمد للاسترجاع')),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            bases=('history.entity',),
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم الصفحة')),
                ('section', models.CharField(blank=True, max_length=240, verbose_name='الموضع / القسم')),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(verbose_name='نص المقطع')),
                ('embedding', models.JSONField(default=list)),
                ('embedding_reference', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.historicalsource')),
            ],
            options={
                'ordering': ['source_id', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('source', 'ordinal'), name='unique_source_ordinal')],
            },
        ),
    ]
