# Generated by Django 5.2.17 on 2026-10-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsource',
            name='url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='رابط المصدر'),
        ),
    ]
