# Generated by Django 5.2.17 on 2026-10-03 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sourceanalysis'),
        ('history', '0005_storypassage'),
        ('sources', '0002_alter_historicalsource_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='المقتطف الحرفي')),
                ('context', models.TextField(blank=True, verbose_name='سياق الذكر')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=12, verbose_name='حالة المراجعة')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sourceanalysis')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentions', to='sources.sourcechunk', verbose_name='المقطع')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_mentions', to='history.entity', verbose_name='الحدث أو الشخصية أو المكان')),
                ('reviewed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentions', to='sources.historicalsource', verbose_name='المصدر')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'entity', 'chunk'), name='unique_source_entity_chunk')],
            },
        ),
    ]
