# Generated by Django 5.2.17 on 2026-10-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_sourcemention'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsource',
            name='replaces',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='sources.historicalsource', verbose_name='إصدار سابق للمصدر'),
        ),
    ]
