# Generated by Django 5.2.17 on 2026-10-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان المحاكاة')),
                ('decision_point', models.TextField(verbose_name='نقطة القرار')),
                ('alternative', models.TextField(verbose_name='البديل الافتراضي')),
                ('possible_consequences', models.TextField(verbose_name='النتائج المحتملة')),
                ('influencing_factors', models.TextField(verbose_name='العوامل المؤثرة')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], default='DRAFT', max_length=12, verbose_name='حالة المراجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='history.historicalevent', verbose_name='الحدث')),
            ],
        ),
    ]
