# Generated by Django 5.2.17 on 2026-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'مستخدم'), ('assistant', 'مرشد')], max_length=12)),
                ('content', models.TextField()),
                ('structured_answer', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('retrieved_source_ids', models.JSONField(default=list)),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('classification', models.CharField(max_length=30)),
                ('confidence', models.CharField(db_index=True, max_length=60)),
                ('needs_review', models.BooleanField(db_index=True, default=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
