# Generated by Django 5.2.17 on 2026-10-03 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الإعداد')),
                ('kind', models.CharField(choices=[('local', 'Ollama'), ('gemini', 'Gemini'), ('openai', 'OpenAI'), ('compatible', 'متوافق مع OpenAI')], max_length=20, verbose_name='المزوّد / البروتوكول')),
                ('base_url', models.URLField(max_length=2048, verbose_name='رابط API الأساسي')),
                ('model', models.CharField(max_length=160, verbose_name='النموذج')),
                ('encrypted_key', models.TextField(blank=True, editable=False)),
                ('timeout_seconds', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(900)], verbose_name='مهلة الطلب بالثواني')),
                ('analysis_chunk_limit', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='المقاطع في دورة تحليل واحدة')),
                ('is_active', models.BooleanField(default=False, editable=False)),
                ('tested_at', models.DateTimeField(editable=False, null=True)),
                ('test_ok', models.BooleanField(default=False, editable=False)),
                ('test_message', models.CharField(blank=True, editable=False, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_ai_provider')],
            },
        ),
    ]
