# Generated by Django 5.2.17 on 2026-10-03 14:15

from django.db import migrations, models
from datetime import timedelta


def recover_saved_answers(apps, schema_editor):
    Log = apps.get_model('ai','AIQueryLog')
    Message = apps.get_model('ai','AIMessage')
    alias = schema_editor.connection.alias
    for log in Log.objects.using(alias).exclude(user_id=None).filter(answer='').iterator():
        questions = list(Message.objects.using(alias).filter(role='user',content=log.question,
            conversation__user_id=log.user_id,conversation__event_id=log.event_id,
            created_at__gte=log.created_at-timedelta(seconds=1),created_at__lte=log.created_at+timedelta(seconds=10))[:2])
        if len(questions)!=1: continue
        replies = list(Message.objects.using(alias).filter(conversation_id=questions[0].conversation_id,role='assistant')[:2])
        if len(replies)==1:
            Log.objects.using(alias).filter(pk=log.pk).update(answer=replies[0].content,structured_answer=replies[0].structured_answer)


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_providerconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiquerylog',
            name='structured_answer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(recover_saved_answers,migrations.RunPython.noop),
    ]
