# Generated by Django 5.2.17 on 2026-10-01 08:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=240, verbose_name='العنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=240, unique=True, verbose_name='الرابط المختصر')),
                ('kind', models.CharField(choices=[('event', 'حدث'), ('person', 'شخصية'), ('place', 'مكان'), ('source', 'مصدر'), ('era', 'حقبة')], editable=False, max_length=10)),
                ('description', models.TextField(blank=True, verbose_name='بين يديك المشهد')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف')], db_index=True, default='DRAFT', max_length=12, verbose_name='حالة النشر')),
                ('is_demo', models.BooleanField(default=False, verbose_name='محتوى تجريبي يحتاج مراجعة')),
                ('ai_suggested', models.BooleanField(default=False, verbose_name='اقتراح ذكاء اصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEra',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.entity')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='بداية الحقبة هـ')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='نهاية الحقبة هـ')),
            ],
            bases=('history.entity',),
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.entity')),
                ('alternative_names', models.CharField(blank=True, max_length=500, verbose_name='أسماء أخرى')),
                ('birth_label', models.CharField(blank=True, max_length=100, verbose_name='الميلاد إن عُرف')),
                ('death_label', models.CharField(blank=True, max_length=100, verbose_name='الوفاة إن عُرفت')),
            ],
            bases=('history.entity',),
        ),
        migrations.CreateModel(
            name='HistoricalPlace',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.entity')),
                ('historical_name', models.CharField(blank=True, max_length=240, verbose_name='الاسم التاريخي')),
                ('modern_name', models.CharField(blank=True, max_length=240, verbose_name='الاسم الحديث')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='خط العرض الموثق')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='خط الطول الموثق')),
                ('significance', models.TextField(blank=True, verbose_name='الأهمية التاريخية')),
            ],
            bases=('history.entity',),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.entity')),
                ('english_title', models.CharField(blank=True, max_length=240, verbose_name='العنوان الإنجليزي')),
                ('narrative', models.TextField(blank=True, verbose_name='ماذا حدث؟')),
                ('hijri_label', models.CharField(blank=True, max_length=100, verbose_name='التاريخ الهجري')),
                ('gregorian_label', models.CharField(blank=True, max_length=100, verbose_name='التاريخ الميلادي')),
                ('year_order', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='سنة الترتيب هـ')),
                ('date_precision', models.CharField(choices=[('exact', 'تاريخ محدد'), ('year', 'السنة فقط'), ('approximate', 'تقريبي'), ('unknown', 'غير محدد')], default='unknown', max_length=15, verbose_name='دقة التاريخ')),
                ('event_type', models.CharField(choices=[('journey', 'رحلة وتحول'), ('battle', 'معركة'), ('treaty', 'عهد وصلح'), ('culture', 'علم وحضارة')], default='journey', max_length=15, verbose_name='نوع الحدث')),
                ('context', models.TextField(blank=True, verbose_name='ما الذي سبق الحدث؟')),
                ('causes', models.TextField(blank=True, verbose_name='الأسباب')),
                ('decisions', models.TextField(blank=True, verbose_name='القرارات')),
                ('consequences', models.TextField(blank=True, verbose_name='النتائج')),
                ('aftermath', models.TextField(blank=True, verbose_name='ما الذي حدث بعد ذلك؟')),
                ('featured_image', models.URLField(blank=True, verbose_name='رابط الصورة HTTPS')),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='history.historicalera', verbose_name='الحقبة')),
                ('related_events', models.ManyToManyField(blank=True, to='history.historicalevent', verbose_name='الأحداث المرتبطة')),
            ],
            options={
                'ordering': ['year_order', 'id'],
            },
            bases=('history.entity',),
        ),
    ]
