# Generated by Django 5.2.17 on 2026-10-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='events', to='sources.historicalsource', verbose_name='المصادر'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='era',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='history.historicalera', verbose_name='الحقبة'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='events', to='history.historicalperson', verbose_name='الشخصيات'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='history.historicalplace', verbose_name='المكان'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='related_events', to='history.historicalplace', verbose_name='الأماكن المرتبطة'),
        ),
    ]
