# Generated by Django 5.2.17 on 2026-10-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_entity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='date_precision',
            field=models.CharField(choices=[('exact', 'تاريخ محدد'), ('year', 'السنة فقط'), ('month', 'الشهر والسنة'), ('approximate', 'تقريبي'), ('unknown', 'غير محدد')], default='unknown', max_length=15, verbose_name='دقة التاريخ'),
        ),
    ]
