# Generated by Django 5.2.17 on 2026-10-02 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_historicalevent_date_precision'),
        ('knowledge', '0003_entityrelationship_supporting_claim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=180, verbose_name='عنوان الفصل')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ترتيب الفقرة')),
                ('text', models.TextField(verbose_name='النص القصصي')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('REVIEW', 'قيد المراجعة'), ('APPROVED', 'معتمد'), ('PUBLISHED', 'منشور'), ('ARCHIVED', 'مؤرشف'), ('REJECTED', 'مرفوض')], default='DRAFT', max_length=12, verbose_name='حالة النشر')),
                ('editorial_key', models.CharField(blank=True, editable=False, max_length=160, null=True, unique=True)),
                ('ai_suggested', models.BooleanField(default=False, verbose_name='اقتراح ذكاء اصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citations', models.ManyToManyField(related_name='story_passages', to='knowledge.historicalclaim', verbose_name='المعلومات والأدلة الداعمة')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_passages', to='history.historicalevent', verbose_name='الحدث')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
    ]
